version: '3'
services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'hello_cafe'
      MYSQL_ROOT_PASSWORD: '1234'
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    ports:
      - '127.0.0.1:3306:3306'
    volumes:
      - ./repository/tables.sql:/docker-entrypoint-initdb.d/tables.sql
